call npm install dts2hx
call npm install source-map-support
call npm install @types/source-map-support
call npm install @types/node
call npm install jasmine
call npm install @types/jasmine
call npx dts2hx source-map-support
call haxelib install hxnodejs
call npx dts2hx node
call npx dts2hx jasmine